### ISSUE TITLE
Audio problem

### ISSUE THREAD

**Issue by alirezamaleky** [Prakaship78/device_xiaomi_laurel_sprout#1]
Hello and thank you so much ❤️
I have big problem with sounds that it have many noises, I think you fixed it v1754 but when I download it I can't flash it with twrp, in installing when step 1/2 completed it show error kDownload... and doesn't installed. I have to download v1141 but this version has speaker bug, I try update with built-in updater but it doesn't work (properly file isn't correct) please update link
Thank you

**Comment by Prakaship78** [comment]
issue is resolved now it is due to the carrier config I edited
